baseurl = "https://brett.is/"
title = "Brett.is"
languageCode = "en-us"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-34513423-1"
disqusShortname = "brettlangdon"

[params]
    customCSS = ["css/lato.css", "css/site.css"]
    name = "Brett Langdon"
    description = "A geek with a blog"
    bio = "A geek with a blog"
    aboutAuthor = "A geek with a blog"
    twitter = "brett_langdon"
    enableRSS = true
    iconFont = "font-awesome"

[social]
    twitter  = "https://twitter.com/brett_langdon"
    github   = "https://github.com/brettlangdon"
    linkedin = "https://www.linkedin.com/in/brettlangdon"
    rss = "https://brett.is/index.xml"
