baseurl = "https://brett.is/"
title = "Brett.is"
languageCode = "en-us"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-34513423-1"
disqusShortname = "brettlangdon"

[params]
    name = "Brett Langdon"
    description = "A geek with a blog"
    bio = "A geek with a blog"
    aboutAuthor = "Brett is a code monkey for hire: <a href=\"https://c653labs.com/\" target=\"_blank\">c653labs.com</a>"
    twitter = "brett_langdon"
    enableRSS = true
    iconFont = "font-awesome"

[social]
    twitter  = "https://twitter.com/brett_langdon"
    github   = "https://github.com/brettlangdon"
    rss = "https://brett.is/index.xml"
